[project]
name = 'Government-Procurement-Platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.award-tracking]
path = 'contracts/award-tracking.clar'
clarity_version = 2
epoch = 2.5

[contracts.bid-submission]
path = 'contracts/bid-submission.clar'
clarity_version = 2
epoch = 2.5

[contracts.evaluation-criteria]
path = 'contracts/evaluation-criteria.clar'
clarity_version = 2
epoch = 2.5

[contracts.rfp-publication]
path = 'contracts/rfp-publication.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
